/* 
 * fraudapi
 *
 * Easily and directly scan and block fraudulent security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.FraudDetection.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.FraudDetection.Model
{
    /// <summary>
    /// Result of performing an advanced document fraud analysis
    /// </summary>
    [DataContract]
    public partial class AdvancedFraudDetectionResult :  IEquatable<AdvancedFraudDetectionResult>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdvancedFraudDetectionResult" /> class.
        /// </summary>
        /// <param name="successful">True if successful, false otherwise.</param>
        /// <param name="cleanResult">True if the document is clean, false if fraud threats were found.</param>
        /// <param name="fraudRiskLevel">Overall fraud risk level between 0.0 and 1.0.</param>
        /// <param name="containsFinancialLiability">True if the document contains financial liability.</param>
        /// <param name="containsSensitiveInformationCollection">True if the document contains sensitive data collection from the recipient.</param>
        /// <param name="containsAssetTransfer">True if the document contains an asset transfer.</param>
        /// <param name="containsPurchaseAgreement">True if the document contains a purchase agreement.</param>
        /// <param name="containsEmploymentAgreement">True if the document contains an employment agreement.</param>
        /// <param name="analysisRationale">Rationale on why the document was classified as such.</param>
        public AdvancedFraudDetectionResult(bool? successful = default(bool?), bool? cleanResult = default(bool?), double? fraudRiskLevel = default(double?), bool? containsFinancialLiability = default(bool?), bool? containsSensitiveInformationCollection = default(bool?), bool? containsAssetTransfer = default(bool?), bool? containsPurchaseAgreement = default(bool?), bool? containsEmploymentAgreement = default(bool?), string analysisRationale = default(string))
        {
            this.Successful = successful;
            this.CleanResult = cleanResult;
            this.FraudRiskLevel = fraudRiskLevel;
            this.ContainsFinancialLiability = containsFinancialLiability;
            this.ContainsSensitiveInformationCollection = containsSensitiveInformationCollection;
            this.ContainsAssetTransfer = containsAssetTransfer;
            this.ContainsPurchaseAgreement = containsPurchaseAgreement;
            this.ContainsEmploymentAgreement = containsEmploymentAgreement;
            this.AnalysisRationale = analysisRationale;
        }
        
        /// <summary>
        /// True if successful, false otherwise
        /// </summary>
        /// <value>True if successful, false otherwise</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// True if the document is clean, false if fraud threats were found
        /// </summary>
        /// <value>True if the document is clean, false if fraud threats were found</value>
        [DataMember(Name="CleanResult", EmitDefaultValue=false)]
        public bool? CleanResult { get; set; }

        /// <summary>
        /// Overall fraud risk level between 0.0 and 1.0
        /// </summary>
        /// <value>Overall fraud risk level between 0.0 and 1.0</value>
        [DataMember(Name="FraudRiskLevel", EmitDefaultValue=false)]
        public double? FraudRiskLevel { get; set; }

        /// <summary>
        /// True if the document contains financial liability
        /// </summary>
        /// <value>True if the document contains financial liability</value>
        [DataMember(Name="ContainsFinancialLiability", EmitDefaultValue=false)]
        public bool? ContainsFinancialLiability { get; set; }

        /// <summary>
        /// True if the document contains sensitive data collection from the recipient
        /// </summary>
        /// <value>True if the document contains sensitive data collection from the recipient</value>
        [DataMember(Name="ContainsSensitiveInformationCollection", EmitDefaultValue=false)]
        public bool? ContainsSensitiveInformationCollection { get; set; }

        /// <summary>
        /// True if the document contains an asset transfer
        /// </summary>
        /// <value>True if the document contains an asset transfer</value>
        [DataMember(Name="ContainsAssetTransfer", EmitDefaultValue=false)]
        public bool? ContainsAssetTransfer { get; set; }

        /// <summary>
        /// True if the document contains a purchase agreement
        /// </summary>
        /// <value>True if the document contains a purchase agreement</value>
        [DataMember(Name="ContainsPurchaseAgreement", EmitDefaultValue=false)]
        public bool? ContainsPurchaseAgreement { get; set; }

        /// <summary>
        /// True if the document contains an employment agreement
        /// </summary>
        /// <value>True if the document contains an employment agreement</value>
        [DataMember(Name="ContainsEmploymentAgreement", EmitDefaultValue=false)]
        public bool? ContainsEmploymentAgreement { get; set; }

        /// <summary>
        /// Rationale on why the document was classified as such
        /// </summary>
        /// <value>Rationale on why the document was classified as such</value>
        [DataMember(Name="AnalysisRationale", EmitDefaultValue=false)]
        public string AnalysisRationale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AdvancedFraudDetectionResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  FraudRiskLevel: ").Append(FraudRiskLevel).Append("\n");
            sb.Append("  ContainsFinancialLiability: ").Append(ContainsFinancialLiability).Append("\n");
            sb.Append("  ContainsSensitiveInformationCollection: ").Append(ContainsSensitiveInformationCollection).Append("\n");
            sb.Append("  ContainsAssetTransfer: ").Append(ContainsAssetTransfer).Append("\n");
            sb.Append("  ContainsPurchaseAgreement: ").Append(ContainsPurchaseAgreement).Append("\n");
            sb.Append("  ContainsEmploymentAgreement: ").Append(ContainsEmploymentAgreement).Append("\n");
            sb.Append("  AnalysisRationale: ").Append(AnalysisRationale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AdvancedFraudDetectionResult);
        }

        /// <summary>
        /// Returns true if AdvancedFraudDetectionResult instances are equal
        /// </summary>
        /// <param name="input">Instance of AdvancedFraudDetectionResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AdvancedFraudDetectionResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.CleanResult == input.CleanResult ||
                    (this.CleanResult != null &&
                    this.CleanResult.Equals(input.CleanResult))
                ) && 
                (
                    this.FraudRiskLevel == input.FraudRiskLevel ||
                    (this.FraudRiskLevel != null &&
                    this.FraudRiskLevel.Equals(input.FraudRiskLevel))
                ) && 
                (
                    this.ContainsFinancialLiability == input.ContainsFinancialLiability ||
                    (this.ContainsFinancialLiability != null &&
                    this.ContainsFinancialLiability.Equals(input.ContainsFinancialLiability))
                ) && 
                (
                    this.ContainsSensitiveInformationCollection == input.ContainsSensitiveInformationCollection ||
                    (this.ContainsSensitiveInformationCollection != null &&
                    this.ContainsSensitiveInformationCollection.Equals(input.ContainsSensitiveInformationCollection))
                ) && 
                (
                    this.ContainsAssetTransfer == input.ContainsAssetTransfer ||
                    (this.ContainsAssetTransfer != null &&
                    this.ContainsAssetTransfer.Equals(input.ContainsAssetTransfer))
                ) && 
                (
                    this.ContainsPurchaseAgreement == input.ContainsPurchaseAgreement ||
                    (this.ContainsPurchaseAgreement != null &&
                    this.ContainsPurchaseAgreement.Equals(input.ContainsPurchaseAgreement))
                ) && 
                (
                    this.ContainsEmploymentAgreement == input.ContainsEmploymentAgreement ||
                    (this.ContainsEmploymentAgreement != null &&
                    this.ContainsEmploymentAgreement.Equals(input.ContainsEmploymentAgreement))
                ) && 
                (
                    this.AnalysisRationale == input.AnalysisRationale ||
                    (this.AnalysisRationale != null &&
                    this.AnalysisRationale.Equals(input.AnalysisRationale))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.CleanResult != null)
                    hashCode = hashCode * 59 + this.CleanResult.GetHashCode();
                if (this.FraudRiskLevel != null)
                    hashCode = hashCode * 59 + this.FraudRiskLevel.GetHashCode();
                if (this.ContainsFinancialLiability != null)
                    hashCode = hashCode * 59 + this.ContainsFinancialLiability.GetHashCode();
                if (this.ContainsSensitiveInformationCollection != null)
                    hashCode = hashCode * 59 + this.ContainsSensitiveInformationCollection.GetHashCode();
                if (this.ContainsAssetTransfer != null)
                    hashCode = hashCode * 59 + this.ContainsAssetTransfer.GetHashCode();
                if (this.ContainsPurchaseAgreement != null)
                    hashCode = hashCode * 59 + this.ContainsPurchaseAgreement.GetHashCode();
                if (this.ContainsEmploymentAgreement != null)
                    hashCode = hashCode * 59 + this.ContainsEmploymentAgreement.GetHashCode();
                if (this.AnalysisRationale != null)
                    hashCode = hashCode * 59 + this.AnalysisRationale.GetHashCode();
                return hashCode;
            }
        }
    }

}
