/* 
 * fraudapi
 *
 * Easily and directly scan and block fraudulent security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Cloudmersive.APIClient.NETCore.FraudDetection.Client;
using Cloudmersive.APIClient.NETCore.FraudDetection.Model;

namespace Cloudmersive.APIClient.NETCore.FraudDetection.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFraudDetectionApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// AI Fraud Detection for Documents
        /// </summary>
        /// <remarks>
        /// Perform fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>FraudDetectionResult</returns>
        FraudDetectionResult DocumentDetectFraud (System.IO.Stream inputFile = null);

        /// <summary>
        /// AI Fraud Detection for Documents
        /// </summary>
        /// <remarks>
        /// Perform fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>ApiResponse of FraudDetectionResult</returns>
        ApiResponse<FraudDetectionResult> DocumentDetectFraudWithHttpInfo (System.IO.Stream inputFile = null);
        /// <summary>
        /// Advanced AI Fraud Detection for Documents
        /// </summary>
        /// <remarks>
        /// Perform advanced fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preprocessing">Optional: Set the level of image pre-processing to enhance accuracy.  Possible values are &#39;Auto&#39; and &#39;None&#39;.  Default is Auto. (optional)</param>
        /// <param name="resultCrossCheck">Optional: Set the level of output accuracy cross-checking to perform on the input.  Possible values are &#39;None&#39; and &#39;Advanced&#39;.  Default is None. (optional)</param>
        /// <param name="userEmailAddress">User email address for context (optional) (optional)</param>
        /// <param name="userEmailAddressVerified">True if the user&#39;s email address was verified (optional) (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>AdvancedFraudDetectionResult</returns>
        AdvancedFraudDetectionResult DocumentDetectFraudAdvanced (string preprocessing = null, string resultCrossCheck = null, string userEmailAddress = null, bool? userEmailAddressVerified = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Advanced AI Fraud Detection for Documents
        /// </summary>
        /// <remarks>
        /// Perform advanced fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preprocessing">Optional: Set the level of image pre-processing to enhance accuracy.  Possible values are &#39;Auto&#39; and &#39;None&#39;.  Default is Auto. (optional)</param>
        /// <param name="resultCrossCheck">Optional: Set the level of output accuracy cross-checking to perform on the input.  Possible values are &#39;None&#39; and &#39;Advanced&#39;.  Default is None. (optional)</param>
        /// <param name="userEmailAddress">User email address for context (optional) (optional)</param>
        /// <param name="userEmailAddressVerified">True if the user&#39;s email address was verified (optional) (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>ApiResponse of AdvancedFraudDetectionResult</returns>
        ApiResponse<AdvancedFraudDetectionResult> DocumentDetectFraudAdvancedWithHttpInfo (string preprocessing = null, string resultCrossCheck = null, string userEmailAddress = null, bool? userEmailAddressVerified = null, System.IO.Stream inputFile = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// AI Fraud Detection for Documents
        /// </summary>
        /// <remarks>
        /// Perform fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>Task of FraudDetectionResult</returns>
        System.Threading.Tasks.Task<FraudDetectionResult> DocumentDetectFraudAsync (System.IO.Stream inputFile = null);

        /// <summary>
        /// AI Fraud Detection for Documents
        /// </summary>
        /// <remarks>
        /// Perform fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>Task of ApiResponse (FraudDetectionResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<FraudDetectionResult>> DocumentDetectFraudAsyncWithHttpInfo (System.IO.Stream inputFile = null);
        /// <summary>
        /// Advanced AI Fraud Detection for Documents
        /// </summary>
        /// <remarks>
        /// Perform advanced fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preprocessing">Optional: Set the level of image pre-processing to enhance accuracy.  Possible values are &#39;Auto&#39; and &#39;None&#39;.  Default is Auto. (optional)</param>
        /// <param name="resultCrossCheck">Optional: Set the level of output accuracy cross-checking to perform on the input.  Possible values are &#39;None&#39; and &#39;Advanced&#39;.  Default is None. (optional)</param>
        /// <param name="userEmailAddress">User email address for context (optional) (optional)</param>
        /// <param name="userEmailAddressVerified">True if the user&#39;s email address was verified (optional) (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>Task of AdvancedFraudDetectionResult</returns>
        System.Threading.Tasks.Task<AdvancedFraudDetectionResult> DocumentDetectFraudAdvancedAsync (string preprocessing = null, string resultCrossCheck = null, string userEmailAddress = null, bool? userEmailAddressVerified = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Advanced AI Fraud Detection for Documents
        /// </summary>
        /// <remarks>
        /// Perform advanced fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preprocessing">Optional: Set the level of image pre-processing to enhance accuracy.  Possible values are &#39;Auto&#39; and &#39;None&#39;.  Default is Auto. (optional)</param>
        /// <param name="resultCrossCheck">Optional: Set the level of output accuracy cross-checking to perform on the input.  Possible values are &#39;None&#39; and &#39;Advanced&#39;.  Default is None. (optional)</param>
        /// <param name="userEmailAddress">User email address for context (optional) (optional)</param>
        /// <param name="userEmailAddressVerified">True if the user&#39;s email address was verified (optional) (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>Task of ApiResponse (AdvancedFraudDetectionResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<AdvancedFraudDetectionResult>> DocumentDetectFraudAdvancedAsyncWithHttpInfo (string preprocessing = null, string resultCrossCheck = null, string userEmailAddress = null, bool? userEmailAddressVerified = null, System.IO.Stream inputFile = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FraudDetectionApi : IFraudDetectionApi
    {
        private Cloudmersive.APIClient.NETCore.FraudDetection.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FraudDetectionApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FraudDetectionApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NETCore.FraudDetection.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NETCore.FraudDetection.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FraudDetectionApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FraudDetectionApi(Cloudmersive.APIClient.NETCore.FraudDetection.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NETCore.FraudDetection.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NETCore.FraudDetection.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NETCore.FraudDetection.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.FraudDetection.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// AI Fraud Detection for Documents Perform fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>FraudDetectionResult</returns>
        public FraudDetectionResult DocumentDetectFraud (System.IO.Stream inputFile = null)
        {
             ApiResponse<FraudDetectionResult> localVarResponse = DocumentDetectFraudWithHttpInfo(inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// AI Fraud Detection for Documents Perform fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>ApiResponse of FraudDetectionResult</returns>
        public ApiResponse< FraudDetectionResult > DocumentDetectFraudWithHttpInfo (System.IO.Stream inputFile = null)
        {

            var localVarPath = "./fraud-ai/detection/document";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DocumentDetectFraud", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<FraudDetectionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (FraudDetectionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(FraudDetectionResult)));
        }

        /// <summary>
        /// AI Fraud Detection for Documents Perform fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>Task of FraudDetectionResult</returns>
        public async System.Threading.Tasks.Task<FraudDetectionResult> DocumentDetectFraudAsync (System.IO.Stream inputFile = null)
        {
             ApiResponse<FraudDetectionResult> localVarResponse = await DocumentDetectFraudAsyncWithHttpInfo(inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// AI Fraud Detection for Documents Perform fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>Task of ApiResponse (FraudDetectionResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<FraudDetectionResult>> DocumentDetectFraudAsyncWithHttpInfo (System.IO.Stream inputFile = null)
        {

            var localVarPath = "./fraud-ai/detection/document";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DocumentDetectFraud", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<FraudDetectionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (FraudDetectionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(FraudDetectionResult)));
        }

        /// <summary>
        /// Advanced AI Fraud Detection for Documents Perform advanced fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preprocessing">Optional: Set the level of image pre-processing to enhance accuracy.  Possible values are &#39;Auto&#39; and &#39;None&#39;.  Default is Auto. (optional)</param>
        /// <param name="resultCrossCheck">Optional: Set the level of output accuracy cross-checking to perform on the input.  Possible values are &#39;None&#39; and &#39;Advanced&#39;.  Default is None. (optional)</param>
        /// <param name="userEmailAddress">User email address for context (optional) (optional)</param>
        /// <param name="userEmailAddressVerified">True if the user&#39;s email address was verified (optional) (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>AdvancedFraudDetectionResult</returns>
        public AdvancedFraudDetectionResult DocumentDetectFraudAdvanced (string preprocessing = null, string resultCrossCheck = null, string userEmailAddress = null, bool? userEmailAddressVerified = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<AdvancedFraudDetectionResult> localVarResponse = DocumentDetectFraudAdvancedWithHttpInfo(preprocessing, resultCrossCheck, userEmailAddress, userEmailAddressVerified, inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Advanced AI Fraud Detection for Documents Perform advanced fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preprocessing">Optional: Set the level of image pre-processing to enhance accuracy.  Possible values are &#39;Auto&#39; and &#39;None&#39;.  Default is Auto. (optional)</param>
        /// <param name="resultCrossCheck">Optional: Set the level of output accuracy cross-checking to perform on the input.  Possible values are &#39;None&#39; and &#39;Advanced&#39;.  Default is None. (optional)</param>
        /// <param name="userEmailAddress">User email address for context (optional) (optional)</param>
        /// <param name="userEmailAddressVerified">True if the user&#39;s email address was verified (optional) (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>ApiResponse of AdvancedFraudDetectionResult</returns>
        public ApiResponse< AdvancedFraudDetectionResult > DocumentDetectFraudAdvancedWithHttpInfo (string preprocessing = null, string resultCrossCheck = null, string userEmailAddress = null, bool? userEmailAddressVerified = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./fraud-ai/detection/document/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (preprocessing != null) localVarHeaderParams.Add("preprocessing", this.Configuration.ApiClient.ParameterToString(preprocessing)); // header parameter
            if (resultCrossCheck != null) localVarHeaderParams.Add("resultCrossCheck", this.Configuration.ApiClient.ParameterToString(resultCrossCheck)); // header parameter
            if (userEmailAddress != null) localVarHeaderParams.Add("UserEmailAddress", this.Configuration.ApiClient.ParameterToString(userEmailAddress)); // header parameter
            if (userEmailAddressVerified != null) localVarHeaderParams.Add("UserEmailAddressVerified", this.Configuration.ApiClient.ParameterToString(userEmailAddressVerified)); // header parameter
            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DocumentDetectFraudAdvanced", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AdvancedFraudDetectionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (AdvancedFraudDetectionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AdvancedFraudDetectionResult)));
        }

        /// <summary>
        /// Advanced AI Fraud Detection for Documents Perform advanced fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preprocessing">Optional: Set the level of image pre-processing to enhance accuracy.  Possible values are &#39;Auto&#39; and &#39;None&#39;.  Default is Auto. (optional)</param>
        /// <param name="resultCrossCheck">Optional: Set the level of output accuracy cross-checking to perform on the input.  Possible values are &#39;None&#39; and &#39;Advanced&#39;.  Default is None. (optional)</param>
        /// <param name="userEmailAddress">User email address for context (optional) (optional)</param>
        /// <param name="userEmailAddressVerified">True if the user&#39;s email address was verified (optional) (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>Task of AdvancedFraudDetectionResult</returns>
        public async System.Threading.Tasks.Task<AdvancedFraudDetectionResult> DocumentDetectFraudAdvancedAsync (string preprocessing = null, string resultCrossCheck = null, string userEmailAddress = null, bool? userEmailAddressVerified = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<AdvancedFraudDetectionResult> localVarResponse = await DocumentDetectFraudAdvancedAsyncWithHttpInfo(preprocessing, resultCrossCheck, userEmailAddress, userEmailAddressVerified, inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Advanced AI Fraud Detection for Documents Perform advanced fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.FraudDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preprocessing">Optional: Set the level of image pre-processing to enhance accuracy.  Possible values are &#39;Auto&#39; and &#39;None&#39;.  Default is Auto. (optional)</param>
        /// <param name="resultCrossCheck">Optional: Set the level of output accuracy cross-checking to perform on the input.  Possible values are &#39;None&#39; and &#39;Advanced&#39;.  Default is None. (optional)</param>
        /// <param name="userEmailAddress">User email address for context (optional) (optional)</param>
        /// <param name="userEmailAddressVerified">True if the user&#39;s email address was verified (optional) (optional)</param>
        /// <param name="inputFile">Input document, or photos of a document, to perform fraud detection on (optional)</param>
        /// <returns>Task of ApiResponse (AdvancedFraudDetectionResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AdvancedFraudDetectionResult>> DocumentDetectFraudAdvancedAsyncWithHttpInfo (string preprocessing = null, string resultCrossCheck = null, string userEmailAddress = null, bool? userEmailAddressVerified = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./fraud-ai/detection/document/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (preprocessing != null) localVarHeaderParams.Add("preprocessing", this.Configuration.ApiClient.ParameterToString(preprocessing)); // header parameter
            if (resultCrossCheck != null) localVarHeaderParams.Add("resultCrossCheck", this.Configuration.ApiClient.ParameterToString(resultCrossCheck)); // header parameter
            if (userEmailAddress != null) localVarHeaderParams.Add("UserEmailAddress", this.Configuration.ApiClient.ParameterToString(userEmailAddress)); // header parameter
            if (userEmailAddressVerified != null) localVarHeaderParams.Add("UserEmailAddressVerified", this.Configuration.ApiClient.ParameterToString(userEmailAddressVerified)); // header parameter
            if (inputFile != null) localVarFileParams.Add("InputFile", this.Configuration.ApiClient.ParameterToFile("InputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DocumentDetectFraudAdvanced", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AdvancedFraudDetectionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (AdvancedFraudDetectionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AdvancedFraudDetectionResult)));
        }

    }
}
